name: baraka30
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.0+1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  quran_flutter: ^1.0.0 
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ADD THIS SECTION:
  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/KFGQPC Uthmanic Script HAFS Regular.otf